name: auto-deploy.yml
# Deploys to Google App Engine upon commit to master branch and on schedule at midnight UTC
run-name: Deployment triggered by ${{ github.event_name }} / ${{ github.actor }}

on:
  push:
    branches:
      - "master"
  schedule:
    - cron: "50 11 * * *"
    # see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  workflow_dispatch:

# Only run 1 workflow at a time. If new one starts abort any that are already running.
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  default-job:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-22.04

    steps:
      - run: echo "Triggered by ${{ github.event_name }} event."

      - name: Check out this repository code
        uses: actions/checkout@v3
        with:
          path: empower
          fetch-depth: 0

      - name: Check out `empower-config` to get env-config
        uses: actions/checkout@v3
        with:
          repository: sentry-sandbox/empower-config
          path: empower-config
          token: ${{ secrets.OGI_PERSONAL_ACCESS_TOKEN_FOR_SYNC_DEPLOY_FORK }}

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Setup Sentry CLI
        uses: mathieu-bour/setup-sentry-cli@v1.3.0
        with:
          version: 2.17.4
          token: ${{ SECRETS.SENTRY_AUTH_TOKEN }} # from GitHub secrets

      - name: Get commit SHA that was last successfully deployed
        uses: nrwl/nx-set-shas@v3.0.1
        with:
          main-branch-name: master
          error-on-no-successful-workflow: false
          working-directory: ./empower

      # Test previous step worked
      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"

      - name: Get env-config/production.env from empower-config
        run: cp empower-config/production.env empower/env-config/

      - name: Deploy to production
        run: |
          CHANGED_PROJECTS="react flask laravel vue vite"
          # CHANGED_PROJECTS=$(./bin/projects_changed_bw_commits.sh "${{ env.NX_BASE }}" "${{ env.NX_HEAD }}")
          if [[ ! -z "$CHANGED_PROJECTS" ]]; then
            ./deploy.sh $CHANGED_PROJECTS --env=production
          elif [[ `./bin/release.sh` != `./bin/release.sh 1` ]]; then # different release than yesterday
            # currently we create regular calendar releases only for React
            ./deploy.sh react --env=production
          else 
            echo "No deployable projects have been changed since last successful deployment. New calendar release is not due either. Nothing to do."
          fi
        working-directory: ./empower

      - run: echo "Job status is ${{ job.status }}."
