name: fork-sync.yml

on:
  schedule:
    - cron: "0 * * * *"
    # runs every hour
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync master with upstream latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          # owner: sentry-sandbox
          base: master
          head: master
